atomeocean/job-compass

- docs/zhHans/index.md
> add homepage logo

- package-lock.json
- package.json
- 集成husky
- prettier
- elementplus icons
> add husky prettier icons

- docs/.vitepress/theme/components/StaffingCompanyInformationTable.vue
- docs/.vitepress/theme/components/TimelineComponent.vue
- docs/.vitepress/theme/index.ts
- docs/zhHans/staffing-company/dream-big-career.md
- 添加新的表格组件，引用了elementplus组件
- 添加时间线组件
> add new table component

- docs/en/direct-hire-company/amazon-inc.md
- docs/zhHans/direct-hire-company/amazon-inc.md
add amazon doc
credit to @tengtianxiang
> copy paste amazon doc

- .github/workflows/notify-direct-hire-company-subscribers.yml
- docs/zhHans/direct-hire-company/atomeocean.md
- 获取在招聘公司目录下的变更文件
- 读取里面的email信息和文件路径
- 修改atomeocean公司资料触发actions
> update github actions

- .github/workflows/notify-direct-hire-company-subscribers.yml
- scripts/notify_direct_hire_company_subscribers.py
1. 去掉引起错误的actions代码
2. 新增script目录用于添加python script
> change to python to execute script

- docs/.vitepress/theme/components/VideoLinks.vue
- docs/zhHans/guide/github-pull-request-guide.md
> add 2 video links

- docs/.vitepress/theme/components/DirectoryTree.vue
- docs/en/job-postings/index.md
目录结构组件添加英文分区
- 关联 Issue: #1234
- **新增**：
- **修复**：
- **优化**：
请描述如何测试本 PR，或提供测试步骤。
1. 运行
```shell
```
是否有任何需要 reviewer 重点关注的地方？
> add en structure

- docs/zhHans/guide/task-guide.md
添加 直招公司信息 任务指南
- 关联 Issue: #1234
- **新增**：
- **修复**：
- **优化**：
请描述如何测试本 PR，或提供测试步骤。
1. 运行
```shell
```
是否有任何需要 reviewer 重点关注的地方？
> 更新job compass任务指南

- docs/zhHans/direct-hire-company/washington/seattle/amazon.md
修改了Amazon亚马逊公司介绍页面的标题
- 关联 Issue: #89
> [快速开始PR]修改页面标题

- docs/zhHans/direct-hire-company/california/san-jose/google.md
- 更新Google公司页面名称
1. 本地运行
```shell
```
> update google company name

- docs/zhHans/direct-hire-company/new-york/new-york/atomeocean.md
- docs/zhHans/direct-hire-company/new-york/new-york/data/atomeocean.json
- docs/zhHans/staffing-company/amaze-systems.md
更新atomeocean公司信息
- **新增**：
1. 本地运行
```shell
```
3. 在new york目录下检查atomeocean页面显示情况
> update atomeocean info

- docs/zhHans/job-postings/Meta/software-engineer-20250313.md
1-line change，修改页面标题
1. 本地运行
```shell
```
> [快速开始]update meta job post

- docs/.vitepress/theme/components/DirectHireCompanyTable.vue
- docs/.vitepress/theme/components/StaffingCompanyTable.vue
- docs/.vitepress/theme/index.ts
- docs/zhHans/staffing-company/antra.md
- docs/zhHans/staffing-company/company-utils/company-info-template.md
- docs/zhHans/staffing-company/data/antra.json
- docs/zhHans/staffing-company/index.md
1. 添加劳务派遣公司信息组件
2. 添加劳务派遣公司信息的markdown模版文件
3. 修改antra信息，查看组件展示效果
- 关联 Issue: 
- **新增**：
- **修复**：
- **优化**：
1. 本地运行
```shell
```
4. 打开浏览器访问 `http://localhost:5173`
> 添加劳务派遣公司信息组件

- .github/ISSUE_TEMPLATE/4_request_to_join_org.yml
添加issue用于新同学加入组织
- 关联 Issue: 
1. 本地运行
```shell
```
> add issue template

- .github/ISSUE_TEMPLATE/4_request_to_join_org.yml
> update issue template

- docs/zhHans/direct-hire-company/company-utils/company-info-guide.md
- docs/zhHans/job-postings/job-postings-utils/job-posting-guide.md
- docs/zhHans/job-postings/job-postings-utils/job-posting-template.md
1. 更新招聘信息模版标题
2. 修改招聘信息指南
- 关联 Issue: 
- **新增**：
- **修复**：
- **优化**：
1. 本地运行
```shell
```
3. 打开浏览器访问 `http://localhost:5173`
> [快速开始] 修改指南标题

- docs/.vitepress/theme/components/ReferenceSource.vue
- docs/.vitepress/theme/index.ts
添加“引用来源” reference source组件，并注册到全局。
- 关联 Issue: 
后续添加内容时可以使用该组件插入引用来源信息
1. 本地运行
```shell
```
> [添加组件]add ref source component

- docs/zhHans/job-postings/Sanzaru-Games/data/narrative-systems-designer-20250403.json
- docs/zhHans/job-postings/Sanzaru-Games/index.md
- docs/zhHans/job-postings/Sanzaru-Games/narrative-systems-designer-20250403.md
> 填写招聘信息 Sanzaru Game Studio

- docs/zhHans/direct-hire-company/new-york/new-york/chubb-limited.md
仅修改chubb公司名字
1. 本地运行
```shell
```
> update chubb name

- docs/zhHans/direct-hire-company/arizona/phoenix/onsemi.md
1 line change，修改标题为公司名字
1. 本地运行
```shell
```
> update onsemi name

- docs/zhHans/job-postings/amazon/software-development-engineer-20250313.md
> fix path error

- docs/zhHans/job-postings/bloomberg/data/senior-full-stack-software-engineer-compliance-applications.json
- docs/zhHans/job-postings/bloomberg/index.md
- docs/zhHans/job-postings/bloomberg/senior-full-stack-software-engineer-compliance-applications.md
根据教程添加一个Bloomberg的在招职位
1. 本地运行
```shell
```
> add a bloomberg job post

- docs/zhHans/guide/task-guide.md
- docs/zhHans/job-postings/job-postings-utils/job-posting-guide.md
- docs/zhHans/job-postings/job-postings-utils/toturial-json-template.md
- 更新职位发布教程
- 将链接改为job compass内部跳转，相比跳到github仓库提高了用户网站留存时间
- 利用markdown语法和vitepress支持实现一键复制模板json，并添加字段解释和示例
1. 本地运行
```shell
```
> update totorial 0419

- docs/zhHans/guide/task-guide.md
直招公司信息路径改为内部跳转
- 关联 Issue: 
1. 本地运行
```shell
```
> change path to local

- docs/zhHans/direct-hire-company/california/san-francisco/cruise-llc.md
提供新pr @tengtianxiang @atomeocean/atomeocean-light-weight 
替换文章中公司名字。
1. 本地运行
```shell
```
> update cruise company info

- docs/zhHans/direct-hire-company/california/los-angeles/coco-robotics.md
> update company name

- docs/zhHans/index.md
> update home page

- docs/zhHans/direct-hire-company/massachusetts/boston/cargurus.md
- docs/zhHans/direct-hire-company/massachusetts/boston/data/cargurus.json
新增cargurus直招公司信息
- 关联 Issue: 
1. 本地运行
```shell
```
> 添加cargurus公司信息

- docs/zhHans/guide/task-guide.md
更新指南，包括其中的路径
- 关联 Issue: 
1. 本地运行
```shell
```
> update starter guide

- docs/zhHans/guide/github-setup-guide.md
补充初始化权限部分
- 关联 Issue: 
1. 本地运行
```shell
```
> update setup guide

- docs/zhHans/guide/markdown-cheatsheet.md
- docs/zhHans/job-postings/job-postings-utils/job-posting-template.md
- docs/zhHans/job-postings/ptc/software-engineer-20250504.md
去掉模板中的emoji
- 关联 Issue: 
1. 本地运行
```shell
```
> remove template emoji

- docs/zhHans/interview-prepare/entry-level-survival-tips.md
> remove outside span

- docs/zhHans/guide/json-cheatsheet.md
添加json cheatsheet中的outline
- 关联 Issue: 
1. 本地运行
```shell
```
> update json cheatsheet

- docs/zhHans/guide/markdown-cheatsheet.md
添加outline
- 关联 Issue: 
1. 本地运行
```shell
```
> update md cheatsheet

- docs/zhHans/job-postings/amazon/data/software-development-engineer-intern-20250506.json
- docs/zhHans/job-postings/amazon/software-development-engineer-20250313.md
- docs/zhHans/job-postings/amazon/software-development-engineer-intern-20250506.md
- 关联 Issue: 
1. 本地运行
```shell
```
> add amazon intern job Posting

- docs/zhHans/guide/directory-structure.md
记录命名规则均为小写单词连接
- 关联 Issue: https://github.com/atomeocean/job-compass/issues/122
1. 本地运行
```shell
```
> add url naming

- docs/zhHans/direct-hire-company/massachusetts/boston/cargurus.md
- docs/zhHans/direct-hire-company/overview.md
> update last updated

- docs/zhHans/index.md
> udpate homepage

- docs/zhHans/index.md
- docs/zhHans/staffing-company/overview.md
> upate staffing card

- docs/en/index.md
> update en index

- docs/zhHans/guide/github-pull-request-guide.md
> update guide md

- docs/en/direct-hire-company/washington/seattle/amazon.md
- docs/en/index.md
> update en card

- docs/zhHans/job-postings/job-postings-utils/job-posting-guide.md
补充job posting指南中公司路径不能大写
- 关联 Issue: 
1. 本地运行
```shell
```
> update job posting guide

- docs/zhHans/direct-hire-company/arizona/phoenix/onsemi.md
修改onsemi公司信息的markdown文件标题
- 关联 Issue: 
1. 本地运行
```shell
```
> 修改onsemi文件标题

- docs/zhHans/index.md
- docs/zhHans/job-postings/overview.md
> update card to homepage

- docs/zhHans/job-postings/apple/data-scientist-20250605.md
- docs/zhHans/job-postings/apple/data/data-scientist-20250605.json
- docs/zhHans/job-postings/apple/data/software-data-engineer-20250605.json
- docs/zhHans/job-postings/apple/software-data-engineer-20250605.md
添加software data engineer的岗位
Create software-data-engineer and data scientist positions
- 关联 Issue: 
1. 本地运行
```shell
```
> Create software-data-engineer and data-scientist positions

- docs/zhHans/job-postings/coreweave/data-engineer-20250605.md
- docs/zhHans/job-postings/coreweave/data/data-engineer-20250605.json
- docs/zhHans/job-postings/coreweave/data/market-intelligence-analyst-20250605.json
- docs/zhHans/job-postings/coreweave/market-intelligence-analyst-20250605.md
为coreweave添加两个新的工作岗位
为CoreWeave 添加两个新的岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> Create market intelligence analyst and data engineer positions

- docs/zhHans/job-postings/mckinsey/data/business-analyst-20250609.json
main分支部署失败，原因是无法正确解析json
本地npm build成功，预览成功
> fix main failure

- docs/zhHans/job-postings/td-bank/business-information-analyst-20250609.md
- docs/zhHans/job-postings/td-bank/data/business-information-analyst-20250609.json
- docs/zhHans/job-postings/td-bank/data/software-engineer-20250609.json
- docs/zhHans/job-postings/td-bank/financial-analyst-20250604.md
- docs/zhHans/job-postings/td-bank/software-engineer-20250609.md
添加td bank的两个新岗位（SDE+ business information analyst）
添加td bank的两个新岗位（SDE+ business information analyst）
- 关联 Issue: 
1. 本地运行
```shell
```
> Create td bank的两个新岗位（SDE+ business information analyst）

- docs/zhHans/job-postings/amazon/business-analyst-20250604.md
- docs/zhHans/job-postings/amazon/data-engineer-20250604.md
- docs/zhHans/job-postings/amazon/data/business-analyst-20250604.json
- docs/zhHans/job-postings/amazon/data/data-engineer-20250604.json
添加amazon的de岗位信息
添加的amazon的两个新岗位 data engineer和data analyst
- 关联 Issue: 
1. 本地运行
```shell
```
> Create data-engineer & business analyst

- docs/zhHans/job-postings/sanzaru-games/data/software-development-engineer-20250606.json
- docs/zhHans/job-postings/sanzaru-games/software-development-engineer-20250606.md
添加Sanzaru Games的一个sde岗位
添加Sanzaru Games的一个sde岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> 添加Sanzaru Games的一个sde岗位

- docs/zhHans/job-postings/databricks/data/research-scientist-20250612.json
- docs/zhHans/job-postings/databricks/data/solutions-engineer-20250612.json
- docs/zhHans/job-postings/databricks/research-scientist-20250612.md
- docs/zhHans/job-postings/databricks/solutions-engineer-20250612.md
创建databricks的两个新岗位(solutions engineer+ research scientist)
创建databricks的两个新岗位(solutions engineer+ research scientist)
- 关联 Issue: 
1. 本地运行
```shell
```
> Create databricks的两个新岗位(solutions engineer+ research scientist)

- docs/zhHans/job-postings/uber/data/staff-software-engineer-20250613.json
- docs/zhHans/job-postings/uber/staff-software-engineer-20250613.md
增加uber岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> add uber job

- docs/zhHans/job-postings/coreweave/business-intelligence-engineer-20250606.md
组件引用路径中的文件名称与对应json文件名不匹配，导致内容无法显示
修复：修改引用路径中的文件名称
- 关联 Issue: 
1. 本地运行
```shell
```
> 修复json文件路径

- docs/zhHans/job-postings/morgan-stanley/data/java-scala-developer-20250616.json
- docs/zhHans/job-postings/morgan-stanley/data/software-developer-20250616.json
- docs/zhHans/job-postings/morgan-stanley/java-scala-developer-20250616.md
- docs/zhHans/job-postings/morgan-stanley/software-engineer-20250616.md
添加Morgan Stanley的两个新岗位（java developer+ai sde）
添加Morgan Stanley的两个新岗位（java developer+ai sde）
- 关联 Issue: 
1. 本地运行
```shell
```
> Create Morgan Stanley的两个新岗位（java developer+ai sde）

- docs/zhHans/career-guide/entry-level-survival-tips.md
替代这个pr https://github.com/atomeocean/job-compass/pull/349
> remove extra tags

- docs/zhHans/job-postings/netflix/analytics-engineer-20250620.md
- docs/zhHans/job-postings/netflix/data/analytics-engineer-20250620.json
- docs/zhHans/job-postings/netflix/data/software-engineer-20250620.json
- docs/zhHans/job-postings/netflix/software-engineer-20250619.md
- docs/zhHans/job-postings/netflix/software-engineer-20250620.md
- docs/zhHans/job-postings/netflix/sofware-engineer-20250619.md
- docs/zhHans/job-postings/netflix/sofware-engineer-20250620.md
创建Netflix的两个岗位（sde+ba）
创建Netflix的两个岗位（sde+ba）
- 关联 Issue: 
1. 本地运行
```shell
```
> Create Netflix的两个岗位（sde+ analytics engineer）

- docs/zhHans/job-postings/ebay/android-software-engineer-20250618.md
- docs/zhHans/job-postings/ebay/data/android-software-engineer-20250618.json
增加ebay安卓开发岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> add ebay job

- docs/zhHans/job-postings/jpmorgan-chase/data/financial-analysis-20250621.json
- docs/zhHans/job-postings/jpmorgan-chase/data/software-engineer-20250621.json
- docs/zhHans/job-postings/jpmorgan-chase/financial-analysis-20250621.md
- docs/zhHans/job-postings/jpmorgan-chase/software-engineer-20250621.md
添加jpmorgan的两个岗位（sde + fa）
添加jpmorgan的两个岗位（sde + fa）
- 关联 Issue: 
1. 本地运行
```shell
```
> Create jpmorgan的两个岗位（sde + fa）

- docs/zhHans/job-postings/morgan-stanley/data/software-engineer-20250602.json
- docs/zhHans/job-postings/morgan-stanley/data/technology-associate-20250602.json
在morgan stanley 职位信息 json 中补充 "notes" 字段
- 关联 Issue: 
1. 本地运行
```shell
```
> 更新 morgan stanley 职位信息 json 文件

- docs/zhHans/job-postings/goldman-sachs/data/financial-analyst-20250602.json
Financial Planning Analyst岗位的内容无法正常加载，原因是json文件未添加后缀名，导致文件无法被读取
修复：添加json后缀名
- 关联 Issue: 
1. 本地运行
```shell
```
> 修复Goldman Sachs json文件

- .github/workflows/validate-json.yml
利用github actions自动检查新增/修改的json文件是否合法
1. 本地运行
```shell
```
> update validate json

- docs/zhHans/staffing-company/mercury.md
只更改markdown文件测试json validation action是否触发
> change md file only

- docs/zhHans/guide/github-setup-guide.md
修改加入github组织的标准流程链接
- 关联 Issue: 
1. 本地运行
```shell
```
> update join sop link

- docs/zhHans/interview-prepare/stay-confident-us-job-hunting.md
验证引用来源组件可以正常使用
- 关联 Issue: 
1. 本地运行
```shell
```
> update ref comp

- docs/zhHans/interview-prepare/stay-confident-us-job-hunting.md
替换引用来源
- 关联 Issue: 
1. 本地运行
```shell
```
> 0705 update ref

- docs/.vitepress/config.ts
- docs/.vitepress/tsconfig.json
- package-lock.json
- package.json
添加git changelog插件需要的依赖。
用以下办法解决typescript编译报错问题
```shell
npm i vitepress-plugin-mermaid mermaid -D
npm install vitepress-i18n
```
1. 本地运行
```shell
```
> 添加git changelog需要的依赖

- docs/.vitepress/theme/constants/contributors.ts
修复作者显示  
https://jobcompass.atomeocean.com/guide/direct-hire-company-utils/company-info-template.html#state-folder-index-md-file
- 关联 Issue: 
1. 本地运行
```shell
```
> try update contributor

- docs/.vitepress/theme/components/JobRecruiterInformation.vue
- docs/.vitepress/theme/index.ts
- docs/zhHans/referral/coco-robotics.md
修复组件名称typo
原有内推信息不显示了，只需要修复组件名称即可
- 关联 Issue: 
1. 本地运行
```shell
```
> fix JobRecruiterInformationTable comp

- docs/zhHans/index.md
首页添加内推卡片
- 关联 Issue: 
1. 本地运行
```shell
```
> add refer card

- docs/.vitepress/config.ts
- docs/_data/contributors.ts
- docs/types/contributors.ts
- docs/types/index.ts
- docs/zhHans/guide/team.md
1. 修复teampage错误
2. 添加头像获取逻辑，优先使用作者自定义头像，其次使用github头像，最后使用atomeocean默认头像
- 关联 Issue: 
1. 本地运行
```shell
```
3. 打开浏览器访问 `http://localhost:5173`
> fix team page bug

- docs/zhHans/job-postings/spotify/backend-engineer-insights-tooling-20250722.md
- docs/zhHans/job-postings/spotify/data/backend-engineer-insights-tooling-20250722.json
增加声破天backend engineer insights tooling 纽约职位
- 关联 Issue: 
1. 本地运行
```shell
```
> add spotify new job

- docs/zhHans/job-postings/mckinsey/data/operation-engineer-20250725.json
- docs/zhHans/job-postings/mckinsey/operation-engineer-20250725.md
增加McKinseyOperation Engineer 岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> add McKinsey job

- docs/zhHans/job-postings/rockstar/data/senior-frontend-engineer-20250721.json
- docs/zhHans/job-postings/rockstar/index.md
- docs/zhHans/job-postings/rockstar/senior-frontend-engineer-20250721.md
新增Rockstar的Senior Frontend Engineer岗位信息
- 关联 Issue: 
1. 本地运行
```shell
```
> Add rockstar's senior frontend engineer position

- docs/.vitepress/theme/components/VideoLinks.vue
- 支持打开相关抖音视频
- 关联 Issue: https://github.com/atomeocean/job-compass/issues/58
1. 本地运行
```shell
```
> updaet video links comp

- docs/zhHans/interview-prepare/8-bit-career.md
添加outline
- 关联 Issue: 
1. 本地运行
```shell
```
> add outline

- docs/zhHans/guide/demo.md
添加发布pr教程的文档，用于演示如何在网页端通过pull request提交内容修改
- 关联 Issue: issue #123
1. 本地运行
```shell
```
> 添加发布pr教程文档

- docs/zhHans/job-postings/rockstar/animation-R&D-programmer-retargeting-20250811.md
- docs/zhHans/job-postings/rockstar/data/animation-R&D-programmer-retargeting-20250811.json
- docs/zhHans/job-postings/rockstar/data/full-stack-developer-20250811.json
- docs/zhHans/job-postings/rockstar/full-stack-developer-20250811.md
新增Rockstar的Full Stack Developer和Animation R&D Programmer: Retargeting职位
- 关联 Issue: 
- [x ] 文档更新
1. 本地运行
```shell
```
> 更新新的Rockstar职位信息

- docs/.vitepress/theme/components/StaffingCompanyTable.vue
- docs/zhHans/staffing-company/pilot.md
1. 去掉StaffingCompanyTable组件的padding部分
2. 尝试添加outline
3. 去掉未排版的文字
1. 本地运行
```shell
```
4. 打开浏览器访问 `http://localhost:5173`
> remove padding

- scripts/convert_html_to_markdown.py
- 添加转换用脚本，将html转换为markdown文件
- 替换其他工具处理这项逻辑
1. 本地运行
```shell
```
> add convert python script

- docs/zhHans/job-postings/jpmorgan-chase/data/software-engineer-20250829.json
- docs/zhHans/job-postings/jpmorgan-chase/software-engineer-20250829.md
创建Jp Morgen 的新sde岗位
- 关联 Issue: 
1. 本地运行
```shell
```
> Create software-engineer-position from jpMorgen

- docs/zhHans/job-postings/job-postings-utils/job-posting-guide.md
- 更新指南文件，添加更多描述
- 关联 Issue: 
1. 本地运行
```shell
```
> add more guide details

- .github/workflows/update-frontmatter.yml
- scripts/git-actions/add_created_date_to_md.py
- scripts/git-actions/add_last_updated_to_md.py
添加git actions脚本，用于在提交pr时自动填充frontmatter中创建日期和最后修改日期的数值
- 关联 Issue: 
1. 本地运行
```shell
```
> 添加git actions脚本

- docs/zhHans/staffing-company/mercury.md
- 修改文章验证actions添加日期
- outline key设置文章导航显示全部标题
> add new pr 0904

- docs/zhHans/interview-experience/fortinet/online-assessment-20250619.md
- 添加一个OA记录
- 引用地址是 https://pastebin.com/305gzf20
> add oa record

- .github/workflows/deploy.yml
- .github/workflows/update-frontmatter.yml
> update actions yml
